const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});try{
 const p=await b.newPage({ignoreHTTPSErrors:true,viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/index.html',async r=>{const res=await r.fetch();await r.fulfill({response:res,body:(await res.text()).replace('window.CosmicAdventureEngine = {','window.__qaState=AdventureState;window.CosmicAdventureEngine = {')});});
 await p.goto('http://127.0.0.1:8765/index.html');await p.waitForFunction(()=>window.CosmicAdventureEngine);
 await p.evaluate(()=>{renderAdventureLevelSelect();showScreen('screen-adventure-select');});assert.equal(await p.locator('.journey-node').count(),8);
 await p.locator('.journey-node[data-level="8"]').click();await p.waitForFunction(()=>window.currentAdventureScene?.levelConfig.id===8&&currentAdventureScene.fallingStones?.length>0);await p.waitForTimeout(3200);
 const cfg=await p.evaluate(()=>{const s=currentAdventureScene,c=s.levelConfig;return {gates:s.gates.length,enemies:s.levelEnemies.length,ice:c.iceTraversal,up:c.ascentRoutes.some(r=>r.at(-1).y<r[0].y),down:c.ascentRoutes.some(r=>r.at(-1).y>r[0].y),terraces:c.gateLocations.every((x,i)=>c.solidSegments.some(t=>x-100>=t.startX&&x+280<=t.endX&&t.y===c.gateHeights[i])),exit:s.exitGroundY===s.groundY+c.exitHeight};});assert.equal(cfg.gates,7);assert(cfg.enemies>=20);for(const key of ['ice','up','down','terraces','exit'])assert(cfg[key],key);
 await p.screenshot({path:'/tmp/glacier-crown-start.png'});
 const hazard=await p.evaluate(()=>{const s=currentAdventureScene,h=s.fallingStones[0];__qaState.isPaused=false;s.dog.body.reset(h.x,h.floor-160);h.clock=300;s.updateAuthoredHazards(0);const warning=h.marker.alpha>.1&&!h.sprite.body.enable;h.clock=1500;s.updateAuthoredHazards(0);__qaState.energy=100;s.isInvulnerable=false;s.dog.body.reset(h.sprite.x,h.sprite.y);s.dog.body.position.set(h.sprite.body.center.x-s.dog.body.width/2,h.sprite.body.center.y-s.dog.body.height/2);s.dog.body.updateCenter();s.physics.overlap(s.dog,h.sprite,(d,o)=>s.handleDogHazardCollision(d,o));return warning&&h.sprite.body.enable&&__qaState.energy===92;});assert(hazard,'warned shard deals damage');
 await p.evaluate(()=>{const s=currentAdventureScene;__qaState.energy=100;s.enemiesGroup.getChildren().forEach(e=>e.disableBody(true,true));s.dog.body.reset(320,s.groundY-75);s.dog.setVelocity(0,0);});await p.waitForFunction(()=>currentAdventureScene.dog.body.blocked.down);
 const landed=await p.evaluate(()=>new Promise(resolve=>{const s=currentAdventureScene,start=s.time.now;s.touchRight=true;s.queueJump();let air=false;const tick=()=>{air ||= s.dog.body.velocity.y < -100;if(s.dog.x>510)s.touchRight=false;const ok=air&&s.dog.x>430&&Math.abs(s.dog.body.bottom-(s.groundY-103))<10&&(s.dog.body.blocked.down||s.dog.body.touching.down);if(ok||s.time.now-start>7000){s.events.off('postupdate',tick);s.clearTouchInputs();resolve(ok);}};s.events.on('postupdate',tick);}));assert(landed,'real first ice-platform jump');
 await p.evaluate(()=>{const s=currentAdventureScene;s.dog.body.reset(7700,s.groundY-620);s.dog.setVelocity(0,0);});await p.waitForTimeout(900);await p.screenshot({path:'/tmp/glacier-crown-descent.png'});
 await p.evaluate(()=>{gameState.adventureLevels[8]={unlocked:true,stars:3,highScore:900,bones:4,diamonds:2};saveState();});await p.reload();await p.waitForFunction(()=>window.CosmicAdventureEngine);assert.equal(await p.evaluate(()=>gameState.adventureLevels[8]?.stars),3,'new Level 8 progress survives old rename migration');
 assert.deepEqual(errors,[]);console.log('Glacier Crown: eight map nodes, seven safe gates, climb/descent routes, 21 enemies, warned shard damage, real first jump, save reload and no browser errors PASS');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
