// Isolated hazard-state and collision fixtures; no claim of full combat completion.
const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720},ignoreHTTPSErrors:true,serviceWorkers:'block'});const errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.route('**/index.html',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('window.CosmicAdventureEngine = {','window.__qaState=AdventureState;window.CosmicAdventureEngine = {')});});await p.goto('http://127.0.0.1:8765/index.html');await p.waitForFunction(()=>window.CosmicAdventureEngine);fs.mkdirSync('artifacts/biome-challenges',{recursive:true});const results=[];
for(const level of [1,4,5,6,7]){
 await p.evaluate(l=>CosmicAdventureEngine.startAdventure(l),level);await p.waitForFunction(l=>window.currentAdventureScene?.levelConfig?.id===l&&currentAdventureScene.biomeChallenges?.length>0,level);await p.waitForTimeout(500);
 const check=await p.evaluate(()=>{const s=currentAdventureScene,h=s.biomeChallenges[0];s.enemiesGroup.getChildren().forEach(e=>e.disableBody(true,true));s.dog.body.reset(h.x,h.floor-55);s.dog.setVelocity(0,0);s.dog.body.setAllowGravity(false);__qaState.isPaused=false;__qaState.energy=100;s.isInvulnerable=false;
  h.clock=100;s.updateBiomeChallenges(0);const warning=h.warning===0||!h.sprite.body.enable;
  h.clock=h.warning+h.active*.4;s.updateBiomeChallenges(0);const active=h.sprite.body.enable,a={x:h.sprite.x,y:h.sprite.y};h.clock=h.warning+h.active*.65;s.updateBiomeChallenges(0);const motion=Math.hypot(h.sprite.x-a.x,h.sprite.y-a.y);
  s.dog.body.reset(h.sprite.body.center.x,h.sprite.body.center.y);s.dog.body.position.set(h.sprite.body.center.x-s.dog.body.width/2,h.sprite.body.center.y-s.dog.body.height/2);s.dog.body.updateCenter();let hit=false;s.physics.overlap(s.dog,h.sprite,(d,z)=>{hit=true;s.handleDogHazardCollision(d,z);});const damage=100-__qaState.energy;
  h.clock=h.period-10;s.updateBiomeChallenges(0);const rest=h.kind==='pendulum'||!h.sprite.body.enable;
  h.clock=h.warning+h.active*.2;s.updateBiomeChallenges(0);s.dog.body.reset(h.x-170,h.floor-75);s.dog.setVelocity(0,0);s.dog.setAlpha(1);s.cameras.main.stopFollow();s.cameras.main.centerOn(h.x+30,h.floor-150);__qaState.isPaused=true;
  return {level:s.levelConfig.id,kind:h.kind,count:s.biomeChallenges.length,warning,active,motion,hit,damage,rest,clock:h.clock,enemies:s.levelConfig.enemies.map(e=>e.skin),mechanicalGuns:s.cannons.length};
 });assert(check.warning&&check.active&&check.hit&&check.damage===8&&check.rest,JSON.stringify(check));assert(check.count>=5);if(['log','spore','pendulum','icicle'].includes(check.kind))assert(check.motion>10);if(level!==5)assert.equal(check.mechanicalGuns,0);
 await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>currentAdventureScene.biomeChallenges[0].clock),check.clock,'Quiz pause freezes hazard clock');await p.screenshot({path:`artifacts/biome-challenges/level-${level}.png`});results.push(check);console.log(level,check.kind,'PASS');
}
assert.equal(new Set(results.map(r=>r.kind)).size,5);assert.equal(errors.length,0,JSON.stringify(errors));fs.writeFileSync('artifacts/biome-challenges/checks.json',JSON.stringify(results,null,2));}finally{await b.close();}})();
